export const healthInfoFormFields = {
  height: {
    label: 'Chiều cao (cm)',
    type: 'number',
    placeholder: 'Nhập chiều cao',
    min: 100,
    max: 250,
    required: true,
  },
  weight: {
    label: 'Cân nặng (kg)',
    type: 'number',
    placeholder: 'Nhập cân nặng',
    min: 30,
    max: 200,
    required: true,
  },
  gender: {
    label: 'Giới tính',
    type: 'select',
    options: [
      { value: 'male', label: 'Nam' },
      { value: 'female', label: 'Nữ' },
    ],
    required: true,
  },
  age: {
    label: 'Tuổi',
    type: 'number',
    placeholder: 'Nhập tuổi',
    min: 16,
    max: 100,
    required: false,
  },
  bodyFatPercent: {
    label: 'Tỷ lệ mỡ (%)',
    type: 'number',
    placeholder: 'Nhập tỷ lệ mỡ',
    min: 0,
    max: 50,
    step: 0.1,
    required: false,
  },
  goal: {
    label: 'Mục tiêu tập luyện',
    type: 'select',
    options: [
      { value: 'WeightLoss', label: 'Giảm cân' },
      { value: 'MuscleGain', label: 'Tăng cơ' },
      { value: 'Health', label: 'Sức khỏe' },
    ],
    required: true,
  },
  experience: {
    label: 'Trình độ tập luyện',
    type: 'select',
    options: [
      { value: 'Beginner', label: 'Người mới' },
      { value: 'Intermediate', label: 'Trung bình' },
      { value: 'Advanced', label: 'Nâng cao' },
    ],
    required: true,
  },
  fitnessLevel: {
    label: 'Mức độ thể lực',
    type: 'select',
    options: [
      { value: 'Low', label: 'Thấp' },
      { value: 'Medium', label: 'Trung bình' },
      { value: 'High', label: 'Cao' },
    ],
    required: true,
  },
  preferredTime: {
    label: 'Thời gian tập ưa thích',
    type: 'select',
    options: [
      { value: 'Morning', label: 'Sáng' },
      { value: 'Afternoon', label: 'Chiều' },
      { value: 'Evening', label: 'Tối' },
    ],
    required: false,
  },
  weeklySessions: {
    label: 'Số buổi tập/tuần',
    type: 'select',
    options: [
      { value: '1-2', label: '1-2 buổi' },
      { value: '3-4', label: '3-4 buổi' },
      { value: '5+', label: '5+ buổi' },
    ],
    required: false,
  },
  medicalHistory: {
    label: 'Tiền sử bệnh lý',
    type: 'textarea',
    placeholder: 'Nhập tiền sử bệnh lý (nếu có)',
    rows: 3,
    maxLength: 1000,
    required: false,
  },
  allergies: {
    label: 'Dị ứng',
    type: 'textarea',
    placeholder: 'Nhập thông tin dị ứng (nếu có)',
    rows: 3,
    maxLength: 500,
    required: false,
  },
};
