export { LandingPage } from './LandingPage';
export { Header } from '../components/Header';
export { HeroSection } from '../components/HeroSection';
export { FeaturesSection } from '../components/FeaturesSection';
export { PackagesSection } from '../components/PackagesSection';
export { GymInfoSection } from '../components/GymInfoSection';
export { TestimonialsSection } from '../components/TestimonialsSection';
export { FAQSection } from '../components/FAQSection';
export { Footer } from '../components/Footer';
